# Generated by Django 4.2.7 on 2023-11-25 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Carrinho"),
                            (2, "Realizado"),
                            (3, "Pago"),
                            (4, "Entregue"),
                        ],
                        default=1,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_pagamento",
                    models.IntegerField(
                        choices=[
                            (1, "Cartão de Crédito"),
                            (2, "Cartão de Débito"),
                            (3, "PIX"),
                            (4, "Boleto"),
                            (5, "Transferência Bancária"),
                            (6, "Dinheiro"),
                            (7, "Outro"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.IntegerField(choices=[(1, "50"), (2, "100"), (3, "150")]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "imagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="uploader.image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("times", models.ManyToManyField(to="RedFox.time")),
            ],
        ),
        migrations.CreateModel(
            name="ItensCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=1)),
                (
                    "preco_item",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="RedFox.compra",
                    ),
                ),
                (
                    "ingresso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="RedFox.ingresso",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingresso",
            name="partida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="RedFox.partida"
            ),
        ),
    ]
